trigger:
  branches:
    include: [ master, dev ]

pr:
  branches:
    include: [ master, dev ]

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: 'CarSimulatorApp.sln'
  webProject: 'CarSimulator.Server/CarSimulator.Server.csproj'

  artifactName: 'drop'
  publishDir: '$(Build.ArtifactStagingDirectory)/web'
  packageZip: '$(Build.ArtifactStagingDirectory)/web.zip'
  serviceConnection: 'SC-carsimdev-tw'
  devWebAppName: 'CarSimDevOps25'
  prodWebAppName: 'CarSimDevOps25'

stages:
# =============== BUILD =================
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs: { packageType: 'sdk', version: '9.0.x' }
    - script: dotnet restore $(solution)
      displayName: 'Restore'
    - script: dotnet build $(solution) -c $(buildConfiguration)
      displayName: 'Build'
    - script: dotnet publish $(webProject) -c $(buildConfiguration) -o $(publishDir)
      displayName: 'Publish web'
    - task: ArchiveFiles@2
      displayName: 'Zip published app'
      inputs:
        rootFolderOrFile: '$(publishDir)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(packageZip)'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(artifactName)'

# ================ TEST =================
- stage: Test
  displayName: 'Test'
  dependsOn: Build
  jobs:
  - job: Tests
    steps:
    - task: UseDotNet@2
      inputs: { packageType: 'sdk', version: '9.0.x' }
    - script: dotnet test $(solution) -c $(buildConfiguration) --logger trx
      displayName: 'dotnet test (solution)'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/*.trx'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        failTaskOnFailedTests: true

# =============== DEPLOY ===============
- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Test
  jobs:
  # DEV
  - deployment: Deploy_Dev
    displayName: 'Deploy to Azure App Service (dev)'
    environment: 'dev'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(artifactName)'
            displayName: 'Download artifact (current run)'
          - task: AzureWebApp@1
            displayName: 'Deploy to $(devWebAppName)'
            inputs:
              azureSubscription: '$(serviceConnection)'
              appName: '$(devWebAppName)'
              package: '$(Pipeline.Workspace)/$(artifactName)/web.zip'

  # MASTER
  - deployment: Deploy_Master
    displayName: 'Deploy to Azure App Service (master)'
    environment: 'prod'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(artifactName)'
            displayName: 'Download artifact (current run)'
          - task: AzureWebApp@1
            displayName: 'Deploy to $(prodWebAppName)'
            inputs:
              azureSubscription: '$(serviceConnection)'
              appName: '$(prodWebAppName)'
              package: '$(Pipeline.Workspace)/$(artifactName)/web.zip'
